import '@/app/globals.css';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-cyan-900 text-cyan-100 font-estedad">{children}</body>
    </html>
  );
}
