import '@/app/globals.css';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body className="bodyLayout">
        <div className="container mx-auto px-4 md:px-0">{children}</div>
      </body>
    </html>
  );
}
